<?php

namespace ContainerRDq7w2n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JzlvJO7Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.JzlvJO7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JzlvJO7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'file' => ['privates', '.errored..service_locator.JzlvJO7.Symfony\\Component\\HttpFoundation\\File\\UploadedFile', NULL, 'Cannot autowire service ".service_locator.JzlvJO7": it references class "Symfony\\Component\\HttpFoundation\\File\\UploadedFile" but no such service exists.'],
        ], [
            'file' => 'Symfony\\Component\\HttpFoundation\\File\\UploadedFile',
        ]);
    }
}
