<?php

namespace ContainerRDq7w2n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MainController::ajustes' => ['privates', '.service_locator.ds7YBVN', 'get_ServiceLocator_Ds7YBVNService', true],
            'App\\Controller\\MainController::ajustes_foto' => ['privates', '.service_locator.ds7YBVN', 'get_ServiceLocator_Ds7YBVNService', true],
            'App\\Controller\\MainController::hombreescort' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\MainController::index' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\MainController::registaracion' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\MainController::userInTown' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SentMailController::index' => ['privates', '.service_locator.A0rcl1e', 'get_ServiceLocator_A0rcl1eService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Service\\FileManagerUp::imagePostUpload' => ['privates', '.service_locator.JzlvJO7', 'get_ServiceLocator_JzlvJO7Service', true],
            'App\\Service\\FileManagerUp::onlyUpload' => ['privates', '.service_locator.JzlvJO7', 'get_ServiceLocator_JzlvJO7Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\MainController:ajustes' => ['privates', '.service_locator.ds7YBVN', 'get_ServiceLocator_Ds7YBVNService', true],
            'App\\Controller\\MainController:ajustes_foto' => ['privates', '.service_locator.ds7YBVN', 'get_ServiceLocator_Ds7YBVNService', true],
            'App\\Controller\\MainController:hombreescort' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\MainController:index' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\MainController:registaracion' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\MainController:userInTown' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SentMailController:index' => ['privates', '.service_locator.A0rcl1e', 'get_ServiceLocator_A0rcl1eService', true],
            'App\\Service\\FileManagerUp:imagePostUpload' => ['privates', '.service_locator.JzlvJO7', 'get_ServiceLocator_JzlvJO7Service', true],
            'App\\Service\\FileManagerUp:onlyUpload' => ['privates', '.service_locator.JzlvJO7', 'get_ServiceLocator_JzlvJO7Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\MainController::ajustes' => '?',
            'App\\Controller\\MainController::ajustes_foto' => '?',
            'App\\Controller\\MainController::hombreescort' => '?',
            'App\\Controller\\MainController::index' => '?',
            'App\\Controller\\MainController::registaracion' => '?',
            'App\\Controller\\MainController::userInTown' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SentMailController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'App\\Service\\FileManagerUp::imagePostUpload' => '?',
            'App\\Service\\FileManagerUp::onlyUpload' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\MainController:ajustes' => '?',
            'App\\Controller\\MainController:ajustes_foto' => '?',
            'App\\Controller\\MainController:hombreescort' => '?',
            'App\\Controller\\MainController:index' => '?',
            'App\\Controller\\MainController:registaracion' => '?',
            'App\\Controller\\MainController:userInTown' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SentMailController:index' => '?',
            'App\\Service\\FileManagerUp:imagePostUpload' => '?',
            'App\\Service\\FileManagerUp:onlyUpload' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
