<?php

namespace ContainerRDq7w2n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteUserControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DeleteUserController' shared autowired service.
     *
     * @return \App\Controller\DeleteUserController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DeleteUserController'] = $instance = new \App\Controller\DeleteUserController(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\DataUserRepository'] ?? $container->load('getDataUserRepositoryService')), ($container->privates['App\\Repository\\FotosRepository'] ?? $container->load('getFotosRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\DeleteUserController', $container));

        return $instance;
    }
}
