<?php

namespace ContainerRDq7w2n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFotosRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FotosRepository' shared autowired service.
     *
     * @return \App\Repository\FotosRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FotosRepository'] = new \App\Repository\FotosRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
