<?php

namespace ContainerRDq7w2n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFotosTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\FotosType' shared autowired service.
     *
     * @return \App\Form\FotosType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\FotosType'] = new \App\Form\FotosType();
    }
}
