<?php

namespace ContainerRDq7w2n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileManagerUpService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Service\FileManagerUp' shared autowired service.
     *
     * @return \App\Service\FileManagerUp
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Service\\FileManagerUp'] = $instance = new \App\Service\FileManagerUp();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Service\\FileManagerUp', $container));

        return $instance;
    }
}
