<?php

namespace ContainerRDq7w2n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MainController' shared autowired service.
     *
     * @return \App\Controller\MainController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MainController'] = $instance = new \App\Controller\MainController(($container->privates['App\\Repository\\ProvinceRepository'] ?? $container->load('getProvinceRepositoryService')), ($container->privates['App\\Repository\\FotosRepository'] ?? $container->load('getFotosRepositoryService')), ($container->privates['App\\Repository\\DataUserRepository'] ?? $container->load('getDataUserRepositoryService')), ($container->services['router'] ?? $container->getRouterService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\MainController', $container));

        return $instance;
    }
}
