<?php

namespace ContainerRDq7w2n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSentMailControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SentMailController' shared autowired service.
     *
     * @return \App\Controller\SentMailController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SentMailController'] = $instance = new \App\Controller\SentMailController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\SentMailController', $container));

        return $instance;
    }
}
