<?php

namespace ContainerRDq7w2n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadedFileService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.JzlvJO7.Symfony\Component\HttpFoundation\File\UploadedFile' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\File\UploadedFile
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.JzlvJO7": it references class "Symfony\\Component\\HttpFoundation\\File\\UploadedFile" but no such service exists.');
    }
}
