<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRDq7w2n\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRDq7w2n/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRDq7w2n.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRDq7w2n\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRDq7w2n\App_KernelProdContainer([
    'container.build_hash' => 'RDq7w2n',
    'container.build_id' => 'fa4f61c1',
    'container.build_time' => 1608465079,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRDq7w2n');
