<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'delete_user' => [[], ['_controller' => 'App\\Controller\\DeleteUserController::index'], [], [['text', '/delete_user']], [], []],
    'ok' => [[], ['_controller' => 'App\\Controller\\DeleteUserController::index_ok'], [], [['text', '/ok']], [], []],
    'delete_foto' => [['id'], ['_controller' => 'App\\Controller\\DeleteUserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete_foto']], [], []],
    'girls' => [[], ['_controller' => 'App\\Controller\\MainController::girls'], [], [['text', '/girls']], [], []],
    'registaracion' => [[], ['_controller' => 'App\\Controller\\MainController::registaracion'], [], [['text', '/registaracion']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], []],
    'hombre_escort' => [[], ['_controller' => 'App\\Controller\\MainController::hombreescort'], [], [['text', '/hombre-escort']], [], []],
    'data' => [[], ['_controller' => 'App\\Controller\\MainController::putdata'], [], [['text', '/data dfgh']], [], []],
    'ajustes' => [[], ['_controller' => 'App\\Controller\\MainController::ajustes'], [], [['text', '/ajustes/']], [], []],
    'show_only_user' => [['province', 'town', 'user_slug'], ['_controller' => 'App\\Controller\\MainController::showOneUser'], [], [['variable', '/', '[^/]++', 'user_slug', true], ['variable', '/', '[^/]++', 'town', true], ['variable', '/', '[^/]++', 'province', true], ['text', '/escort']], [], []],
    'ussprov' => [['province'], ['_controller' => 'App\\Controller\\MainController::showUsersByProvince'], [], [['text', '/escort'], ['variable', '/', '[^/]++', 'province', true]], [], []],
    'fotos' => [[], ['_controller' => 'App\\Controller\\MainController::ajustes_foto'], [], [['text', '/fotos']], [], []],
    'avisolegal' => [[], ['_controller' => 'App\\Controller\\MainController::avisolegal'], [], [['text', '/aviso-legal']], [], []],
    'polpri' => [[], ['_controller' => 'App\\Controller\\MainController::polprivacidad'], [], [['text', '/politica-privacidad']], [], []],
    'town_escort' => [['slugtown', 'town'], ['_controller' => 'App\\Controller\\MainController::userInTown'], [], [['variable', '/', '[^/]++', 'town', true], ['text', '/escort'], ['variable', '/', '[^/]++', 'slugtown', true]], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'sent_mail' => [[], ['_controller' => 'App\\Controller\\SentMailController::index'], [], [['text', '/email']], [], []],
    'sitemap_site' => [[], ['_controller' => 'App\\Controller\\SitemapSiteController::index'], [], [['text', '/s']], [], []],
    'test' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/test']], [], []],
];
